In [178]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn. ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

digits = load_digits()

In [179]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size = 0.3)


In [194]:
lr = LogisticRegression(max_iter=1000)
lr.fit(X_train,y_train)
lr.score(X_test, y_test)

0.9148580968280468

In [181]:
svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)


0.9833333333333333

In [182]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9722222222222222

In [183]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [184]:
for train_index , test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [185]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)



In [186]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits = 3)


In [187]:
scores_1 = []
scores_svm = []
scores_rf = []

for train_index, test_index in kf.split(digits.data):
     X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]

     scores_1.append(get_score(LogisticRegression(), X_train, X_test, y_train, y_test))
     scores_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))
     scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

c:\Users\trand\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\trand\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://sciki

In [188]:
scores_1

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [189]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [190]:
scores_rf

[0.9398998330550918, 0.9482470784641068, 0.9115191986644408]

In [191]:
from sklearn.model_selection import cross_val_score
cross_val_score(LogisticRegression(max_iter=1000), digits.data, digits.target)

array([0.92222222, 0.87222222, 0.94150418, 0.94150418, 0.89693593])

In [192]:
cross_val_score(SVC(), digits.data, digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [193]:
cross_val_score(RandomForestClassifier(n_estimators=5), digits.data, digits.target)

array([0.82777778, 0.79444444, 0.89972145, 0.92200557, 0.80779944])